const data = {
  products: [
    {
      name: "Nim Shirt",
      slug: "nikeslim-shirt",
      category: "Shirts",
      image: "/images/1.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality shirt",
    },
    {
      name: "Ni Shirt",
      slug: "nikeslim-shirt",
      category: "Shirts",
      image: "/images/2.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality shirt",
    },
    {
      name: "Nike whiteShirt",
      slug: "nikeslim-shirt",
      category: "Shirts",
      image: "/images/3.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality shirt",
    },
    {
      name: "Nike grey Shirt",
      slug: "nikeslim-shirt",
      category: "Shirts",
      image: "/images/4.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality shirt",
    },
  ],
};
export default data;
